force-app/main/default/objects/To_Do__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to display whether the To-Do is completed or not</description>
    <inlineHelpText>Is your To-Do Completed?</inlineHelpText>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>The date by which the to-do task should be completed.</description>
    <inlineHelpText>Enter the Due Date for To-Do</inlineHelpText>
    <label>Due Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Represents the priority level of the task.</description>
    <inlineHelpText>Set the Priority for To-Do</inlineHelpText>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of To-Do that we are creating</description>
    <inlineHelpText>Select the type of To-Do Task.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Household</fullName>
            </value>
            <value>
                <fullName>Hobbies</fullName>
            </value>
            <value>
                <fullName>Self-Improvement</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TodoController.cls
public with sharing class TodoController {

    public class Filters {
        @AuraEnabled
        public String searchKey { get; set; }

        @AuraEnabled
        public String[] types { get; set; }

        @AuraEnabled
        public String[] priorities { get; set; }

        @AuraEnabled
        public String sortBy { get; set; }
    }

    @AuraEnabled(Cacheable=true scope='global')
    public static TodoCardListData getTodoData(Filters filters, Integer pageSize, Integer pageNumber) {
        String key = '';
        String whereClause = '';
        String sortByString = '';
        String[] types, priorities, criteria = new List<String>{};

        if (filters != null) {
            types = filters.types;
            priorities = filters.priorities;
            sortByString = filters.sortBy;

            if (!String.isEmpty(filters.searchKey)) {
                key = '%' + filters.searchKey + '%';
                criteria.add('Name LIKE :key');
            }
            if (filters.types != null) {
                types = filters.types;
                criteria.add('Type__c IN :types');
            }
            if (filters.priorities != null) {
                priorities = filters.priorities;
                criteria.add('Priority__c IN :priorities');
            }

            if (criteria.size() > 0) {
                whereClause = 'WHERE ' + String.join(criteria, ' AND ');
            }
        }

        Integer offset = (pageNumber - 1) * pageSize;

        TodoCardListData result = new TodoCardListData();
        result.pageSize = pageSize;
        result.pageNumber = pageNumber;
        result.totalItemCount = Database.countQuery('SELECT COUNT() FROM To_Do__c ' + whereClause);
        result.records = Database.query(
            'SELECT Id, Name, Type__c, Priority__c, Due_Date__c, Description__c, Completed__c FROM To_Do__c ' +
            whereClause +
            ' ORDER BY '+sortByString+' LIMIT :pageSize OFFSET :offset'
        );
        return result;
    }

    
    @AuraEnabled(cacheable = true)
    public static List<To_Do__c> getDatatableTodos(Integer pageNumber) {
        
        Integer offset = (pageNumber - 1) * 10;
        return [
            SELECT Id, Name, Type__c, Priority__c, Due_Date__c, Description__c, Completed__c
            FROM To_Do__c ORDER BY Name LIMIT 10 OFFSET :offset
        ];
    }

    @AuraEnabled
    public static string updateTodos(Object updatedData){
        System.debug('Inside updateContacts method');

        List<To_Do__c> updatedTodos = (List<To_Do__c>)JSON.deserialize(
            JSON.serialize(updatedData, true), 
            List<To_Do__c>.class
        );
        try {
            update updatedTodos;
            System.debug('Successfully updated the Todos!!');
            return 'Success: Todo(s) updated successfully';
        } catch (Exception e) {
            return 'The following exception has occurred: ' + e.getMessage();
        }
    }
}